### ISSUE TITLE
tooltip triggers mouseout event

### ISSUE THREAD

**Issue by f-scholer** [joewalnes/smoothie#102]
I had problems with the tooltip only showing when moving the mouse. It turns out that the tooltip div element itself triggered the mouseout event, The fix is just to prevent the tooltip from getting pointer events:

SmoothieChart.prototype.getTooltipEl = function () {
....
	  this.tooltipEl.style.pointerEvents = 'none';   <--- add this line

**Comment by drewnoakes** [comment]
Good point. Can you make a PR please?

**Comment by paccerdk** [comment]
I've made a pull request, took me 1 minute via the github webinterface - however it took me a lot longer to track down the issue ;)
