### ISSUE TITLE
only scroll x axis when new data is pushed to timeSeries

### ISSUE THREAD

**Issue by mjkkirschner** [joewalnes/smoothie#103]
This may be an unsupported use case for this library, but curious if I am missing an option somewhere. I am pushing data from a simulator into a time series. The timestamps are not in sync with the real time, and so after a few seconds the data is out of range of the current x axis range and I can no longer see my data:  I am adding data slower than I am scrolling.

What I would like to do is only scroll when I push new data to the timeSeries so that the newest data is always in view. Is this possible?

**Comment by HolgerJeromin** [comment]
Have you tried to `stop()` the chart when you have no data?

**Comment by annazhelt** [comment]
There is an option called nonRealtimeData in v1.34 that might be what you are looking for.

**Comment by WofWca** [comment]
Close?
