### ISSUE TITLE
stream jumpy on the right end with non-real time data

### ISSUE THREAD

**Issue by zuliani71** [joewalnes/smoothie#110]
I am getting data from an external device that streams its data on a TCP/IP socket. The data is sampled once at second.
I succesfully captured and injected that data inside a smoothie time serie.
The timestamps are not in sync with the real time and to overcome the problem I've used the 
the nonRealtimeData option that helped me to corretly see the scrolling time serie on my browser.
I'm pretty happy of the result but the chart doesn't look like a continual stream but very jumpy on the right hand side. I see to  get around this I need to add a delay to the chart. I've tried that but without any result.

I'm able to run the smoothie examples and I can see the effect of adding a delay on them but on my chart this solution doesn't work. May be that is caused by the nonRealtimeData option I'm using with my data.

Is there some extra hiden option I need to use?

**Comment by thiswallz** [comment]
use the delay option

**Comment by zuliani71** [comment]
Hi thiswallz, thanks for answering.
I've already tried with the delay option but no changes. I think the delay option doesn't work if the nonRealtimeData option is enabled

**Comment by WofWca** [comment]
Can you set `nonRealtimeData` back to `false`?
If this is not enough, see if you can convert the data you get to real-time.
