### ISSUE TITLE
Smoothie charts render differently if I open another tab or scroll up/down

### ISSUE THREAD

**Issue by francobottero** [joewalnes/smoothie#118]
I've been experiencing this bug where the chart renders a lot more points when I open a new tab, or when I scroll up/down very quickly. Any thoughts of what could be ?

I upload some screenshots so you can see more clearly : 

![Captura de Pantalla 2019-11-28 a la(s) 13 15 53](https://user-images.githubusercontent.com/47894601/69821063-5df6f180-11e1-11ea-85d7-0471c37a4401.png)

![Captura de Pantalla 2019-11-28 a la(s) 13 16 42](https://user-images.githubusercontent.com/47894601/69821050-57687a00-11e1-11ea-9fa7-ed3e99590664.png)

**Comment by HolgerJeromin** [comment]
This is probably a problem with power optimisation from the browser:

https://developers.google.com/web/updates/2017/03/background_tabs

**Comment by HolgerJeromin** [comment]
Fast scrolling does not allow enough cpu cycle to fullfill the settimeout/requestAnimationFrame timers

**Comment by francobottero** [comment]
Thank you for your help !
Im glad to say I fixed the issue by limiting the FPS ! Now my charts are rendered correctly !
