### ISSUE TITLE
Release? Pre-release?

### ISSUE THREAD

**Issue by WofWca** [joewalnes/smoothie#124]
I noticed there's a plenty of new changes since `1.35.0`. Any plans on when they're going to be released?

Maybe at least publish the new changes as `1.36.0-beta.1` or `1.36.0-rc.1` or something like that?

**Comment by drewnoakes** [comment]
Let's get #131 merged and I'll put an update out here. Thanks for your contributions and patience.

**Comment by drewnoakes** [comment]
I'm happy with that, based on the quality of your contributions. It's @joewalnes's project, so it's his call.

**Comment by drewnoakes** [comment]
Version 1.36.0 is up on NPM. Please let me know if you have any issues with it. Thanks all for your help and patience.

**Comment by WofWca** [comment]
Hey, thanks for the collaboration invite, it is an honor!
