### ISSUE TITLE
Can not load smoothie.js

### ISSUE THREAD

**Issue by Radio-Op** [joewalnes/smoothie#129]
Hello,
I have too little knowledge of Javascript..
It seems that smoothie.js does not load as <src> when my index.html is delivered by my node.js tiny http server.
It works when the index.html is opened alone.
It does not work when i try the code online too. (tryit editor)

Best regards.
V.

**Comment by HolgerJeromin** [comment]
What is the error message in the devTools console?

**Comment by Radio-Op** [comment]
> What is the error message in the devTools console?

Hi.
Thanks for answering sir.
I have round a solution after someone on another forum said that smoothie does not work with node.js http server.
It's now ok with an Apache2 server.

**Comment by Radio-Op** [comment]
Closed
