### ISSUE TITLE
Calculate and display average value

### ISSUE THREAD

**Issue by drewnoakes** [joewalnes/smoothie#34]
Only data points which are visible on the chart are kept in memory. We could run an average on these (essentially a time-boxed moving average determined by the speed/width of the chart) and display the average as a horizontal line.

An advanced form of this may be a moving average series, where the window size is independent of the chart speed/width. This may be better suited as an advanced example of using the chart, especially if the framework would not require modification.

**Comment by WofWca** [comment]
Sounds like something outside of the scope of the library. Users can do this by themselves just fine.
