### ISSUE TITLE
Sizing issues with Retina MacBook

### ISSUE THREAD

**Issue by chriscareycode** [joewalnes/smoothie#44]
The canvas seems to double in size and the max/min numbers are off the canvas on Retina displays. This can be seen simply by visiting http://smoothiecharts.org/ on a Retina Mac.

**Comment by eeve** [comment]
@drewnoakes 
@joewalnes 

In response mode, this bug still exists

<img width="1407" alt="11" src="https://user-images.githubusercontent.com/16770728/33300074-709c13bc-d429-11e7-8353-6666b883ad4d.png">
