### ISSUE TITLE
the line is horizontal in the plot, but console.log show the value change rapidly

### ISSUE THREAD

**Issue by xiongzhp** [joewalnes/smoothie#58]

**Comment by drewnoakes** [comment]
What timestamp are you using for points in the series? The chart plots data
using the browser's local time, so make sure you add points using an
appropriate JavaScript Date value.

**Comment by xiongzhp** [comment]
I have solved it, thanks anyway. The problem is that I plot it in requestAnimFrame() function.

**Comment by WofWca** [comment]
Close this?
