### ISSUE TITLE
Is there a way to play/pause the real time chart?

### ISSUE THREAD

**Issue by didip** [joewalnes/smoothie#60]
Since smoothie.js does not have mouseover tooltip feature (and it may not be all that useful because data moves too fast)...

Is there a way to play/pause the real time chart?

**Comment by saarijoki** [comment]
http://jsfiddle.net/drewnoakes/ZWHbm/

**Comment by drewnoakes** [comment]
@didip I'm closing this. Let me know if you think it should stay open.
