### ISSUE TITLE
Rendering is off if canvas element isn't naturally sized

### ISSUE THREAD

**Issue by valtron** [joewalnes/smoothie#64]
On https://github.com/joewalnes/smoothie/blob/master/smoothie.js#L571, `dimensions` should use `canvas.width`/`canvas.height`.

In my use case, the `canvas` element is sized responsively (`width: 100%`, that sort of stuff) and in the case that its actual dimensions don't match the element's `width` and `height` attributes, the chart is squeezed or stretched.

**Comment by drewnoakes** [comment]
You're right. Currently the library requires the canvas to have a fixed size. There was a time when I looked into this and I don't remember exactly the problem I encountered with making this truly dynamic. I think it may have been that there's no reliable way to be notified that the canvas has changed size and needs to be repainted, which causes weird artefacts when the width/height is being stretched.

**Comment by valtron** [comment]
Well, I changed the `dimensions` like I said and it seems to fix it without any artifacts while resizing.

**Comment by mg1075** [comment]
For charts, a responsive chart is a near must-have these days. The proposed fix here does not seem ideal, at least as I'm trying to play around with it. Sure would be nice if the library itself was responsive out of the box.

**Comment by drewnoakes** [comment]
This is now supported. See http://smoothiecharts.org/examples/responsive.html
