### ISSUE TITLE
Data blips on Chart

### ISSUE THREAD

**Issue by Shrest** [joewalnes/smoothie#66]
Hi,
    Thanks for the library.
Im working on plotting data stream received through a web socket using smoothie.js. Able to get the plot on the web browser, but there are blips in the chart and it is occurring more or less consistently about every 30secs. I looked at the data output on the server terminal (raspberry pi) and it is fine. So, not sure, what is causing these blips.
I tried changing the chart update rates, it didn't help.

Request some advise on getting over this.

Thanks.

**Comment by drewnoakes** [comment]
Can you post a screenshot showing what these blips look like?

**Comment by Shrest** [comment]
Sure, but I can't at the moment. I will do it once I get access to my RPi.
However, I will try to describe whats happening.
The reading is about 0.45 to 0.35 and the plot varying uniformly in this interval, but abruptly it changes to 2 (sometimes 360) for an odd sample and immediately comes back to its original data :0.45 to 0.35.
On careful observation I find it repeats every 30 secs (approx.).
Ensured its fine on the server side, no blips over there during observation over extended period.

**Comment by drewnoakes** [comment]
Try writing values to the JavaScript console at the same time as you add
them to the TimeSeries.

**Comment by Shrest** [comment]
I tried writing values to html page. The feed has the blips and smoothie is only displaying what is fed. Seems to be issue with the interlink - websocketd. I don't yet.

Thanks drewnoakes. My apologises for bringing this up, in what seems to be not a smoothie issue.

**Comment by drewnoakes** [comment]
The main thing is that you got it working.
