### ISSUE TITLE
Plotting with Time on x-axis 

### ISSUE THREAD

**Issue by Shrest** [joewalnes/smoothie#67]
I have plotted data stream from web socket on a chart, with x-axis values defined by new Date().getTime().
- Is it possible to plot with time as hh:mm:ss?
- And how to label x and y-axis?

Thanks.

**Comment by drewnoakes** [comment]
To show time values on the x-axis:

    new SmoothieChart({timestampFormatter:SmoothieChart.timeFormatter});

To label x/y axes, superimposing DOM elements is probably easiest. There's no way of doing this that's built in.
