### ISSUE TITLE
Scaling problem

### ISSUE THREAD

**Issue by Erwin4** [joewalnes/smoothie#70]
Hey i was using your library for a little project and i just couldn't get the chart to fit in the container. This was only when the container was set with a percentage. When i used absolute numbers there wasn't an issue.

After exploring a little bit through your library i found that it couldn't get the height and width attributes.

I fixed the problem by just getting the width and height from the id's, but this ofcourse isn't a fix for the library.

**In Smoothiechart.prototyppe.resize = function() -at line 438**

```
var dpr = window.devicePixelRatio;
//var width = parseInt(this.canvas.getAttribute('width')); //getting NaN
//var height = parseInt(this.canvas.getAttribute('height')); //getting NaN

var width = document.getElementById("chart-div").width; //added these as a fix
var height = document.getElementById("chart-div").height; //added these as a fix

if (!this.originalWidth || (Math.floor(this.originalWidth * dpr) !== width)) {
  this.originalWidth = width;
  this.canvas.setAttribute('width', (Math.floor(width * dpr)).toString());
  this.canvas.style.width = width + 'px';
  this.canvas.getContext('2d').scale(dpr, dpr);
}

if (!this.originalHeight || (Math.floor(this.originalHeight * dpr) !== height)) {
  this.originalHeight = height;
  this.canvas.setAttribute('height', (Math.floor(height * dpr)).toString());
  this.canvas.style.height = height + 'px';
  this.canvas.getContext('2d').scale(dpr, dpr);
}
```

**Comment by drewnoakes** [comment]
This is now supported. See http://smoothiecharts.org/examples/responsive.html
