### ISSUE TITLE
No continuse animatied faram

### ISSUE THREAD

**Issue by mkeyno** [joewalnes/smoothie#72]
hi @joewalnes ,  @mape @imrehg @ngd  @pftg  guys, I interested to  use this very lightweight library for manual frame control ,I mean append data with manual textbox event , in another word , insert one data , then redraw the chart and then,  stop until new event data ,I mean stop continues frame animation, but when I disable  'window.setTimeout(function() ' in ' SmoothieChart.AnimateCompatibility = (function())' , code ease to function 
any your any comments  is really appreciated

**Comment by WofWca** [comment]
I think you mean the `nonRealTime` option.
