### ISSUE TITLE
Pause and play !

### ISSUE THREAD

**Issue by seniDEac** [joewalnes/smoothie#74]
Hi every body,

This Feature is a very good one!  
and I ussing it! 

But, when I push to start it again ....  the entire graphics "jumps" to "actual time" .

is it possible to just stop it all? for real?  like.. if I had a "lack" of time?

Tks! Sena,

**Comment by TempestSpectre** [comment]
I hope this helps you :D 

http://jsfiddle.net/drewnoakes/ZWHbm/

**Comment by Yamamila** [comment]
thanks TempestSpectre, 

but I managed in other way!

[]S sena
