### ISSUE TITLE
responsive charts

### ISSUE THREAD

**Issue by mg1075** [joewalnes/smoothie#78]
It would be awesome if smoothie charts could be updated to be responsive. Looks like there have been a few investigations into this in the past, yet nothing has come of it.

**Comment by mg1075** [comment]
This is a proposed hack in a very simplistic form...

The smoothie charts builder page on the smoothie website sort of has a responsive nature in how you can customize the width and the height of a chart.

Now, if the requirement is to have responsive width for a chart, how about listening to the window resize event, and then adjusting the chart width **attribute** on resize?

```
  $( window ).resize(function() {
    var y = $( window).width();
    $('#chart').attr('width', y-50 );
  });
```

**Comment by ChisholmKyle** [comment]
I'm not sure if changing the attribute is any different from changing the width property of the canvas element directly in Javascript, but I made a CodePen that adjusts the chart width for a window.onresize event and scale teh height to a quarter of the width: http://codepen.io/anon/pen/MpWvjX
This implementation doesn't seem to have the problem you describe. It does flicker during the resize if you move it around a lot though.

**Comment by ChisholmKyle** [comment]
I updated the example to not have a container (only the smoothie chart canvas):
http://codepen.io/anon/pen/XMbpWX

**Comment by drewnoakes** [comment]
This is now supported. See http://smoothiecharts.org/examples/responsive.html
