### ISSUE TITLE
Why the chart is not responsive in larger resolution than 300px X 150px?

### ISSUE THREAD

**Issue by notalentgeek** [joewalnes/smoothie#81]
Here is my codes.

    <div style="display:flex;flex:1;flex-direction:row;">
      <canvas id="pitch_graph" style="flex:1;"></canvas>
    </div>

I set the `verticalSections:2`. Here is what happen in smaller resolution.

![http://i.imgur.com/ULkLgh2.png](http://i.imgur.com/ULkLgh2.png)

Which is fine. However, when I scaled the window, the `verticalSections` appeared to be off and not scaled properly.

![http://i.imgur.com/VNiJz4W.png](http://i.imgur.com/VNiJz4W.png)

How can I have the chart to be responsive with any size?

**Comment by drewnoakes** [comment]
This is now supported. See http://smoothiecharts.org/examples/responsive.html

**Comment by notalentgeek** [comment]
Thanks!!!!!
