### ISSUE TITLE
Method append doesn't work

### ISSUE THREAD

**Issue by felipefonsecabh** [joewalnes/smoothie#86]
Hi, i try to use Smoothie, but the append method doesn't work.

I make the initializations in document.ready method:

```
$(document).ready(function(){
        var smoothie = new SmoothieChart({
        millisPerPixel:51,
        //maxValueScale:1.40,
        //minValueScale:1.37,
        interpolation:'linear',
        //scaleSmoothing:0.035,
        grid:{
            fillStyle:'#ffffff',
            strokeStyle:'rgba(119,119,119,0.90)',
            sharpLines:true,
            millisPerLine:4000,
            verticalSections:13
        },
        labels:{fillStyle:'#000000'},
        tooltip:true,
        timestampFormatter:SmoothieChart.timeFormatter
        //maxValue: 40,
        //minValue: 10
        });
       var Temp1 = new TimeSeries();
       smoothie.addTimeSeries(Temp1,{lineWidth:2,strokeStyle:'#214dbe'});
       smoothie.streamTo(document.getElementById('schart'),158);
       setInterval(refreshCharts,800,areaChartInstance,Temp1);
});

function refreshCharts(Temp1){
   //get time and y value
   Temp1.append(new Date.getTime(), y);
}
```

Is any wrong?

**Comment by drewnoakes** [comment]
What is `refreshCharts`?

**Comment by felipefonsecabh** [comment]
I fix the code. RefreshCharts is the function called in setinterval. 
I make a test now print the length of timeseries. It always shows 0.

**Comment by drewnoakes** [comment]
Should you be passing `areaChartInstance` to `setInterval`?

**Comment by felipefonsecabh** [comment]
I do some other stuff in document.ready and in refreshcarts. I put here a part of code, to facilitate the analysys.

**Comment by drewnoakes** [comment]
I think `Temp1` ends up being `areaChartInstance`, not your time series.

At any rate, `append` works correctly. You have a bug in your code.

**Comment by felipefonsecabh** [comment]
The problem was a format Datetime. Do you have a source code of a responsive example? In site doesn't have the file.
Sorry for my mistake.

**Comment by drewnoakes** [comment]
Include `{responsive:true}` in your chart options.
