### ISSUE TITLE
Tool tips not working when multiple charts used on a page

### ISSUE THREAD

**Issue by drewnoakes** [joewalnes/smoothie#88]
From the mailing list:

> I found smoothie charts and I'm trying to build an application that will use multiple charts in a dashboard.  An issue I have run into is being able to display a tool tip for each chart/graph.  The examples only show you how to use the following, but it only works for a single chart/graph.  Once a second chart/graph is added it breaks the tooltip on all the charts.  How can this be modified to work for multiple charts/graphs (like four)?
> 
> ```css
> div.smoothie-chart-tooltip {
>   background: #444;
>   padding: 1em;
>   margin-top: 20px;
>   font-family: consolas;
>   color: white;
>   font-size: 10px;
>   pointer-events: none;
> }
> ```

@Sly1024 have you observed this behaviour?

**Comment by Sly1024** [comment]
@drewnoakes - The way I did it is intentionally using one DOM element for the tooltip of all the charts. After all, you can have the mouse pointer over one chart at a time, so there is only one tooltip visible. That [DOM element is added](https://github.com/Sly1024/pigod/blob/6aef145e632585feec0d8c7dfaba2ea2525eb42f/static/smoothie.js#L478-L482) to the `<body>` tag with `position: absolute;` and hidden by default. When a `mousemove` happens I display the element and [calculate its desired position](https://github.com/Sly1024/pigod/blob/6aef145e632585feec0d8c7dfaba2ea2525eb42f/static/smoothie.js#L544-L547) then set its `left` and `top` styles to move it relative to the `<body>`. 

So as long as the calculation is correct, the tooltip should be displayed correctly.

I'm sorry, I didn't have time to try the latest smoothie chart version with my app.

**Comment by drewnoakes** [comment]
Fixed in 1.33, available on npm. Thanks to @jpmbiz70 for helping with the fix.

**Comment by HolgerJeromin** [comment]
fixed by #89
