### ISSUE TITLE
Bug where series jumps between itself and another series

### ISSUE THREAD

**Issue by eddiew** [joewalnes/smoothie#90]
I'm seeing a bug that manifests like this:
![smoothie-bug](https://user-images.githubusercontent.com/1779397/33414387-299b18d6-d547-11e7-9aed-c986920729da.PNG)

Sometimes a time series will jump between its own value and another series' value, creating weird filled-in sections of the chart. Additionally, this jumping seems to be able to occur retroactively.

**Comment by drewnoakes** [comment]
Can you share some code that reproduces this? I can't imagine why this is happening.

**Comment by eddiew** [comment]
I'll work on finding a minimum example to reproduce this, but for now my hunch is that the issue arises from a race condition in calling TimeSeries.append to different series concurrently.

**Comment by eddiew** [comment]
Turns out that smoothie was not the culprit. I had a bug with the file tailer I was using
