### ISSUE TITLE
CPU load example graphics breaks when scrollBackwards:true

### ISSUE THREAD

**Issue by beikeland** [joewalnes/smoothie#98]
<img width="401" alt="2017-12-27 03_55_34-fakecpu html" src="https://user-images.githubusercontent.com/2701678/34369735-cd6d6a04-eabe-11e7-87b8-f0a7b6d38b79.png">

In testing other modifications i tried running the CPU load example backwards to see where my labels went. When `fillStyle `is set the rendering of the series breaks down with artifacts as shown. Without `fillStyle `in the `seriesOptions` its okay. Possibly related to #65 ?

**Comment by WofWca** [comment]
Closed by #108
